---
- name: runc restart mysql
  command: "{{item}}"
  with_items:
    - runc kill mysql
    - runc delete mysql
    - runc start -d mysql & > /dev/null < /dev/null
  args:
    chdir: /home/ubuntu/mysql
  become: true

  - name: runc restart wordpress
  command: "{{item}}"
  with_items:
    - runc kill wordpress
    - runc delete wordpress
    - runc start -d wordpress & > /dev/null < /dev/null
  args:
    chdir: /home/ubuntu/wordpress
  become: true