---
- name: Gather facts for every host
  hosts: all

- hosts: "{{ target | default('target') }}"
  roles:
  - docker
  - criu
  - route
  - rsync-config
  - namespace
  - pam-limits
  - memcached
  - stack
  - HAproxy


- hosts: "{{ source | default('source') }}"
  roles:
  - docker
  - criu
  - route
  - namespace
  - pam-limits
  - memcached
  - stack
  - HAproxy