---

# clean up script - kills all tools, removes useless stuffs

# container
- name: Kill CRIU processes
  command: pkill -f criu
  become: true
  ignore_errors: yes

- name: Stop MySQL container
  command: runc kill -a mysql
  become: true
  ignore_errors: yes

- name: Stop WordPress container
  command: runc kill -a wordpress
  become: true
  ignore_errors: yes

- name: Remove MySQL container
  command: runc delete -f mysql
  become: true
  ignore_errors: yes

- name: Remove WordPress container
  command: runc delete -f wordpress
  become: true
  ignore_errors: yes

# images
- name: Delete MySQL image
  file: path=/home/ubuntu/mysql state=absent
  become: true

- name: Delete WordPress image
  file: path=/home/ubuntu/wordpress state=absent
  become: true

# ports
- name: Kill socat processes
  command: pkill -f socat
  become: true
  ignore_errors: yes

- name: Remove migrate-target.py bound to port 8888
  command: fuser -k -n tcp 8888
  become: true
  ignore_errors: yes

# iptables
- name: Delete DNAT
  command: "iptables -t nat -D PREROUTING -d {{ hostvars[source].private_address }} -p tcp --dport 80 -j DNAT --to-destination {{ hostvars[target].private_address }}"
  become: true
  ignore_errors: yes

- name: Delete mark
  command: "iptables -t mangle -D PREROUTING -d {{ hostvars[source].private_address }} -p tcp --dport 80 -j MARK --set-mark 0x1"
  become: true
  ignore_errors: yes

- name: Delete forwarding port 80 to target
  command: "iptables -D FORWARD -d {{ hostvars[target].private_address }} -p tcp --dport 80 -j ACCEPT"
  become: true
  ignore_errors: yes

- name: Delete forwarding port 80 from target
  command: "iptables -D FORWARD -s {{ hostvars[target].private_address }} -p tcp --sport 80 -j ACCEPT"
  become: true
  ignore_errors: yes

- name: Delete SNAT
  command: "iptables -t nat -D POSTROUTING -m mark --mark 0x1 -j SNAT --to-source {{ hostvars[source].private_address }}"
  become: true
  ignore_errors: yes

# namespace
- name: Create mysql network namespace
  script: ns.sh
  environment:
    NS: mysql
    VETH: vethmysql
    VPEER: vpeermysql
    VETH_ADDR: 10.200.1.1
    VPEER_ADDR: 10.200.1.2
    BRIDGE_NAME: netbridge
    BRIDGE_ADDR: 10.200.1.3
  become: true

- name: Create wordpress network namespace
  script: ns.sh
  environment:
    NS: wordpress
    VETH: vethwordpress
    VPEER: vpeerwordpress
    VETH_ADDR: 10.200.1.4
    VPEER_ADDR: 10.200.1.5
    BRIDGE_NAME: netbridge
    BRIDGE_ADDR: 10.200.1.3
  become: true

# rsync
- name: Kill rsync processes
  command: pkill -f rsync
  become: true
  ignore_errors: yes